server:
  port: 8081

spring:
  mail:
    default-encoding: UTF-8
    username: ${wht.back.qq}@qq.com
    password: vpvjfotrejnkjgch
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    host: smtp.qq.com
    port: 587
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
  profiles:
    active: auth,perm,data
  main:
    allow-bean-definition-overriding: true

wht:
  fga:
    url: http://114.116.9.68:8082
  api:
    url: https://api.oioweb.cn
  back:
    domain: www.wanghongtao.xyz
    qq: 1946066280
    endpoint: 114.116.9.68