name: Release
on:
  repository_dispatch:
    types: [ semantic-release ]
  push:
    branches:
      - main
      - "*.x" # maintenance releases such as 15.x

jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
    - name: first_step
    env:
      START_STR: Hi!
      USER_NAME: WHT
    run: |
      echo $START_STR $USER_NAME
  second_job:
    name: My Second Job
    needs: first_job
    runs-on: ubuntu-latest
    run: |
      echo 'Hello'
