name: Release
on:
  repository_dispatch:
    types: [ semantic-release ]
  push:
    branches:
      - main
    paths:
      - 'src/main/**'

jobs:
  if_merged:
    name: scan if merged
    if: github.repository == 'OutOfEastGate/TestRelease'
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo The PR was merged
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name: 拉取最新提交的代码
        uses: actions/checkout@v3

      - name: 设置jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: 执行测试
        run: mvn package -DskipTests=true

#       - name: 上传报告到Codecov
#         uses: codecov/codecov-action@v3
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}

#       - name: 项目打包
#         run: mvn package
